spring:

  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    username: root
    password: ${PASSWORD}
    url: jdbc:mariadb://localhost:3307/shop

  jpa:
    hibernate:
      ddl-auto: none